version: '3'

services:
    app:
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        image: coinbox/app
        container_name: coinbox_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - coinbox_network
        depends_on:
            - mysql

    web:
        image: nginx:alpine
        container_name: coinbox_web
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - '9000:80'
            - '9003:443'
        networks:
            - coinbox_network
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: coinbox_mysql
        ports:
            - '9006:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
        volumes:
            - mysql_vol:/var/lib/mysql
            - ./.docker/mysql:/etc/mysql/conf.d
        networks:
            - coinbox_network

networks:
    coinbox_network:
        driver: bridge

volumes:
    mysql_vol:
        driver: local
