version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    image: theta/app
    container_name: theta_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - theta_network
    depends_on:
      - mysql
      - redis

  web:
    image: nginx:alpine
    container_name: theta_web
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./.docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - '80:80'
      - '443:443'
    networks:
      - theta_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: theta_mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - theta_db_vol:/var/lib/mysql
      - ./.docker/mysql:/etc/mysql/conf.d
    networks:
      - theta_network

  redis:
    image: 'redis:alpine'
    container_name: 'theta_redis'
    ports:
      - '6379:6379'
    volumes:
      - theta_cache_vol:/data
    networks:
      - theta_network

networks:
  theta_network:
    driver: bridge

volumes:
  theta_db_vol:
    driver: local
  theta_cache_vol:
    driver: local
