name: Deploying

on:
  push:
    branches: [ main ]

env:
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
  AWS_HOST: ${{ secrets.AWS_HOST  }}
  AWS_USERNAME: ${{ secrets.AWS_USERNAME  }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: try to build
        run: docker-compose build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${AWS_HOST}
          username: ${AWS_USERNAME}
          key: ${AWS_PRIVATE_KEY}
          script: |
            cd /var/www
            git pull origin main


